spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/skill_server}
    username: ${POSTGRES_USERNAME:skill}
    password: ${POSTGRES_PASSWORD:skill}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
